apiVersion: v1
kind: ServiceAccount
metadata:
  name: cube-control-sa
  namespace: domino
---
# Namespace full control
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cube-control-namespace-admin
  namespace: domino
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cube-control-namespace-binding
  namespace: domino
subjects:
  - kind: ServiceAccount
    name: cube-control-sa
    namespace: domino
roleRef:
  kind: Role
  name: cube-control-namespace-admin
  apiGroup: rbac.authorization.k8s.io
---
# Cluster read-only access (nodes etc.)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cube-control-cluster-read
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cube-control-cluster-read-binding
subjects:
  - kind: ServiceAccount
    name: cube-control-sa
    namespace: domino
roleRef:
  kind: ClusterRole
  name: cube-control-cluster-read
  apiGroup: rbac.authorization.k8s.io
